export class CloudflareError extends Error {
  readonly rayId: string | null
  readonly status: number

  constructor(status: number, rayId: string | null = null) {
    super(`Cloudflare error ${status}${rayId ? ` (Ray ID: ${rayId})` : ''}`)
    this.name = 'CloudflareError'
    this.status = status
    this.rayId = rayId
    // Restore prototype chain (required when extending built-ins in TypeScript)
    Object.setPrototypeOf(this, CloudflareError.prototype)
  }
}

export function isCloudflareError(e: unknown): e is CloudflareError {
  return e instanceof CloudflareError
}

// Cloudflare's own origin-connectivity error codes (521-527, 530) plus 520
// ("unknown error") — these are only ever generated by Cloudflare's edge,
// never by our origin server. Deliberately excludes 502/503/504: those are
// generic HTTP statuses our own origin can return on its own (app crash,
// bad gateway from an internal proxy, etc.), so treating them as
// Cloudflare's fault would misattribute a real origin outage. Single
// source of truth — was previously duplicated (and had drifted out of
// sync) between ChaosOps/src/lib/api.ts and chaosops-landing/src/lib/api.ts.
export const CLOUDFLARE_ERROR_STATUSES = new Set([520, 521, 522, 523, 524, 525, 526, 527, 530])

export function isCloudflareErrorStatus(status: number): boolean {
  return CLOUDFLARE_ERROR_STATUSES.has(status)
}
